#!/usr/bin/env python3
"""Week 3 — real-content comparison harness: MediaPipe AutoFlip vs ClipAI.

For every clip in ``tests/real_content/manifest.json``:

  1. Load the cached AutoFlip JSON timeline from
     ``tests/autoflip_reference_outputs/<slug>.json`` (generated by
     ``reference/autoflip/run_one.sh`` on the one-time Docker build).
  2. Build a ClipAI timeline in the same JSON shape — via the
     ``export_autoflip_compatible`` translator over a cached
     extraction (see below), or skipped with a note when the
     pipeline can't be invoked in the current environment.
  3. Optionally load a human ground-truth sidecar from
     ``tests/real_content/ground_truth/<slug>.json``.
  4. Score every available timeline with
     ``autoflip_parity_metrics.cut_to_hold_ratio`` plus the acceleration
     / jerk / overlap metrics.
  5. Emit a per-content-type markdown rollup to
     ``docs/week3_real_content_results.md`` and a raw JSON dump to
     ``/tmp/week3_results.json`` (or wherever ``--json-out`` points).

Usage:

    python -m backend.scripts.compare_autoflip_vs_clipai \\
        --manifest tests/real_content/manifest.json \\
        --autoflip-outputs tests/autoflip_reference_outputs/ \\
        --output docs/week3_real_content_results.md \\
        --json-out /tmp/week3_results.json

Optional flags:

    --filter "panel_*"         Only score clips whose slug matches the glob
    --clipai-only              Skip AutoFlip load (useful before cache
                               regeneration)
    --dry-run                  Enumerate clips + skip the ClipAI pipeline
                               call (fast iteration on the scoring layer)

Design notes:

  - The harness NEVER invokes the Docker MediaPipe runner directly.
    That's expensive and environment-dependent; the cached JSON is
    the supported comparison input. A missing cache file is a
    reported "skipped" row, not a failure.

  - The ClipAI pipeline invocation goes through
    ``run_clipai_on_clip(clip, video_path, cache_dir=…)`` which
    runs the full extraction stack (shots → dense faces → face
    registry → transcript → active speaker → content profile →
    anime anchors → reframe segments) against the resolved video
    path. The extracted features are cached by sha256 under
    ``$CLIPAI_REAL_CONTENT_CACHE/extractions/<sha>/`` so a second
    run against the same clip short-circuits to the cached segment
    list. When the manifest's video is missing on disk the clip is
    reported as ``clipai_skipped``; when ``--dry-run`` is passed the
    helper falls back to a synthetic one-frame-per-source-frame
    timeline for scoring-layer iteration.
"""
from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import logging
import os
import shutil
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("compare_autoflip_vs_clipai")


# ─────────────────── Extraction cache contract ───────────────────
#
# Bump this when the extraction contract changes so stale caches
# get invalidated automatically. See ``run_clipai_on_clip`` for the
# cache layout and file list.
#
# Version history:
#   v1 — initial schema (shots, faces, registry, transcript, speaker
#        events, content_profile, anime_anchors, segments)
#   v2 — Task 0: motion_path persisted inside segments.json so the
#        diagnostic preview renderer reads the same per-frame camera
#        path the production export pipeline uses.
#   v3 — Task 2: per-frame data files added (face_bboxes_per_frame,
#        saliency_peaks_per_second, text_regions_per_frame,
#        identity_timeline) so real-content metrics can be measured.
#   v4 — Task 1: editorial discontinuity_marks recorded so the L1
#        solver and the renderer apply consistent cuts.
#   v5 — Task C: asd_scores.json persisted when the Light-ASD backend
#        is active so re-runs can reuse cached per-frame speaking
#        probabilities instead of paying the inference cost twice.
#   v6 — Layer 1 (critic engine): saliency_peaks_per_second.json is
#        produced from AvSaliency / TASED-Net so the saliency-in-crop
#        critic check has data to work with. The file is required when
#        ``CLIPAI_SALIENCY_LAYER=1`` (default); a previously-valid v5
#        cache without the file is invalidated under the new default.
EXTRACTION_CACHE_VERSION = 6

# Modules whose mtime participates in cache invalidation. If any of
# these files is newer than the cache's ``cache_version.txt`` then
# the cache is considered stale and gets rebuilt from scratch.
#
# Task A expanded this list to include every module whose output gets
# persisted into the cache. The previous list missed Tasks 0/1/2/C
# plumbing — every patch on those tasks shipped behind a cache that
# didn't notice. If you add a module that touches cached state, add
# its path here.
_EXTRACTOR_MODULES_FOR_CACHE = (
    # Original watch list — extractor primitives.
    "backend/services/face_detector.py",
    "backend/services/shot_detector.py",
    "backend/services/transcription.py",
    "backend/services/face_registry.py",
    "backend/services/active_speaker.py",
    "backend/services/content_classifier.py",
    "backend/services/anime_anchor.py",
    "backend/services/reframe_segmenter.py",
    # ── Added Task A ─────────────────────────────────────────────
    "backend/services/l1_camera_path.py",          # writes motion_path
    "backend/services/_autoflip_lp.py",            # LP solver schema
    "backend/services/editorial_planner.py",       # discontinuity_marks
    "backend/services/editorial_subject_lookup.py",
    "backend/services/light_asd.py",               # v3 ASD output shape
    "backend/services/clip_scoring.py",            # finalize/composite
    "backend/services/clip_verifier.py",           # score_diagnostics
    "backend/services/saliency_tracker.py",        # per-second peaks
    "backend/services/av_saliency.py",             # AV saliency mass
    "backend/services/ocr_regions.py",             # text regions
    "backend/scripts/compare_autoflip_vs_clipai.py",   # serialization itself
    "backend/scripts/export_autoflip_compatible.py",   # event translation
    "backend/scripts/sota_render_preview.py",          # diagnostic renderer
)

# Tracks watch-list paths that have already produced a "missing
# module" warning so the log doesn't spam once per cache check.
_WARNED_MISSING_MODULES: set = set()

# Required files inside ``$CACHE/<sha>/`` for a cache hit. The
# presence of every one of these (plus ``cache_version.txt``) is a
# necessary — but not sufficient — condition for cache validity.
#
# ``asd_scores.json`` is conditionally required (Task C): it is only
# expected when ``CLIPAI_ASD_BACKEND=light_asd`` is the active
# backend. ``_required_cache_files()`` resolves the conditional set
# at validity-check time; switching backends invalidates affected
# clips because the cache lacks the required file.
_REQUIRED_CACHE_FILES = (
    "metadata.json",
    "shots.json",
    "dense_faces.json",
    "face_registry.json",
    "transcript.json",
    "speaker_events.json",
    "content_profile.json",
    "anime_anchors.json",
    "segments.json",
    "cache_version.txt",
)


def _active_asd_backend() -> str:
    """Resolve the current ASD backend (defaults to ``light_asd``)."""
    return os.environ.get("CLIPAI_ASD_BACKEND", "light_asd").lower()


def _saliency_layer_enabled() -> bool:
    """Layer 1 toggle. Default ON — the cache always writes
    ``saliency_peaks_per_second.json`` (empty list on extraction
    failure) so the schema stays consistent regardless of whether the
    TASED-Net adapter is actually installed on the host.
    """
    return os.environ.get("CLIPAI_SALIENCY_LAYER", "1") == "1"


def _required_cache_files() -> tuple:
    """Required-file list, with the conditional Task C / Layer 1 entries."""
    base = list(_REQUIRED_CACHE_FILES)
    if _active_asd_backend() == "light_asd":
        base.append("asd_scores.json")
    if _saliency_layer_enabled():
        base.append("saliency_peaks_per_second.json")
    return tuple(base)


# ─────────────────── Target zones (Part D6) ───────────────────
#
# Fallback bands used when a human ground-truth sidecar is not
# available for a clip. A clip PASSES when its median_hold_sec falls
# inside the target range AND its segments_under_1s_rate is under the
# allowed ceiling. Jalon can tune these after the first real run.

# Task 4: every zone now also bounds the four real-content metrics
# (face_clipping_rate, saliency_in_crop_fraction, text_region_clipping_rate,
# identity_switch_count). Genre-appropriate values: panel/animation_dialogue
# stricter on face clipping; sports looser; music_video looser on text.
# Metric thresholds default to the values in the prompt's Task 4 spec.
TARGET_ZONES: dict[str, dict[str, float]] = {
    "multi_speaker_panel": {
        "median_hold_min": 3.0,
        "median_hold_max": 6.0,
        "under_1s_max": 0.05,
        "face_clipping_rate_max": 0.05,
        "saliency_in_crop_min": 0.80,
        "text_clipping_rate_max": 0.05,
        "identity_switch_per_min_max": 2.0,
    },
    "animation": {
        # Action anime: short cuts are the norm
        "median_hold_min": 0.8,
        "median_hold_max": 2.0,
        "under_1s_max": 0.10,
        "face_clipping_rate_max": 0.10,
        "saliency_in_crop_min": 0.65,
        "text_clipping_rate_max": 0.10,
        "identity_switch_per_min_max": 5.0,
    },
    "animation_dialogue": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
        "face_clipping_rate_max": 0.05,
        "saliency_in_crop_min": 0.80,
        "text_clipping_rate_max": 0.05,
        "identity_switch_per_min_max": 2.0,
    },
    "sports_basketball": {
        "median_hold_min": 1.5,
        "median_hold_max": 3.5,
        "under_1s_max": 0.10,
        "face_clipping_rate_max": 0.15,
        "saliency_in_crop_min": 0.60,
        "text_clipping_rate_max": 0.10,
        "identity_switch_per_min_max": 5.0,
    },
    "sports_racing": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
        "face_clipping_rate_max": 0.15,
        "saliency_in_crop_min": 0.60,
        "text_clipping_rate_max": 0.10,
        "identity_switch_per_min_max": 5.0,
    },
    "sports": {
        "median_hold_min": 2.0,
        "median_hold_max": 4.5,
        "under_1s_max": 0.08,
        "face_clipping_rate_max": 0.15,
        "saliency_in_crop_min": 0.60,
        "text_clipping_rate_max": 0.10,
        "identity_switch_per_min_max": 5.0,
    },
    # Music video is handled with a subtype split below; these are
    # the defaults when no subtype is pinned.
    "music_video": {
        "median_hold_min": 1.0,
        "median_hold_max": 4.5,
        "under_1s_max": 0.15,
        "face_clipping_rate_max": 0.10,
        "saliency_in_crop_min": 0.65,
        "text_clipping_rate_max": 0.20,
        "identity_switch_per_min_max": 5.0,
    },
    "music_video_performance": {
        "median_hold_min": 1.0,
        "median_hold_max": 2.5,
        "under_1s_max": 0.15,
        "face_clipping_rate_max": 0.10,
        "saliency_in_crop_min": 0.65,
        "text_clipping_rate_max": 0.20,
        "identity_switch_per_min_max": 5.0,
    },
    "music_video_narrative": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
        "face_clipping_rate_max": 0.10,
        "saliency_in_crop_min": 0.70,
        "text_clipping_rate_max": 0.20,
        "identity_switch_per_min_max": 3.0,
    },
    # Default zone — used when target_clipcontenttype is unknown so
    # verdicts never come back UNKNOWN for a successful run.
    "default": {
        "median_hold_min": 1.5,
        "median_hold_max": 5.5,
        "under_1s_max": 0.10,
        "max_acceleration": 15.0,
        "max_jerk": 15.0,
        "face_clipping_rate_max": 0.10,
        "saliency_in_crop_min": 0.65,
        "text_clipping_rate_max": 0.10,
        "identity_switch_per_min_max": 5.0,
    },
}


# Layer 2 (DOVER) verdict thresholds. Applied via ``verdict_for`` to
# every zone — a reframe that drops aesthetic OR technical score by
# more than the absolute threshold downgrades a PASS verdict to
# MARGINAL. Zones can override by setting their own
# ``quality_delta_aesthetic_min`` / ``quality_delta_technical_min``
# keys (negative numbers; e.g. ``-0.10`` means "delta must be ≥ -0.10
# to keep PASS"). The diagnostics router populates the metrics dict
# with ``quality_delta_aesthetic`` / ``_technical`` after the DOVER
# phase runs. When those keys are absent (bench-only run, layer
# disabled, model missing) the L2 gate is a no-op.
L2_QUALITY_DELTA_AESTHETIC_MIN = -0.10
L2_QUALITY_DELTA_TECHNICAL_MIN = -0.10


def target_zone_for(clip: dict) -> dict[str, float]:
    """Look up the target zone for a clip, falling back through
    (clipcontenttype + subtype) → clipcontenttype → "default" zone.

    Task 4: this never returns ``None`` anymore — unknown content
    types fall back to the ``"default"`` zone so verdicts cannot be
    UNKNOWN for a clip that ran successfully.
    """
    ct = clip.get("target_clipcontenttype") or ""
    sub = clip.get("subtype") or ""
    if ct == "music_video" and sub:
        key = f"music_video_{sub}"
        if key in TARGET_ZONES:
            return TARGET_ZONES[key]
    if ct in TARGET_ZONES:
        return TARGET_ZONES[ct]
    return TARGET_ZONES["default"]


# ─────────────────── Scoring ───────────────────


@dataclass
class ClipResult:
    slug: str
    content_type: str
    target_clipcontenttype: str
    subtype: Optional[str]
    autoflip: Optional[dict[str, Any]] = None
    clipai: Optional[dict[str, Any]] = None
    ground_truth: Optional[dict[str, Any]] = None
    verdicts: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    # Task 5A — which tool produced the AutoFlip column. One of
    # "autoflip_real", "autoflip_prebuilt", "naive_baseline", or None
    # when no AutoFlip JSON was found. The rollup uses this to label
    # "AutoFlip (real)" vs "AutoFlip (naive)" so SOTA claims aren't
    # made against a strawman comparator.
    autoflip_tool: Optional[str] = None
    # Layer 1+ critic engine summary. Populated post-scoring by the
    # main loop. Per-layer subkeys:
    #   "saliency": {"in_crop_fraction": float | None, ...}
    # Layers 2-5 add their own subkeys in subsequent PRs. ``None`` here
    # means the critic engine was disabled or no layer ran.
    critic: Optional[dict[str, Any]] = None


def _derive_crop_centers_pct(events: list[dict]) -> list[float]:
    """Per-event crop_cx in percent (0-100) for the parity metrics."""
    return [float(e.get("crop_cx", 0.5)) * 100.0 for e in events]


def score_timeline(
    events: list[dict],
    *,
    face_bboxes_per_frame: Optional[list] = None,
    saliency_peaks_per_second: Optional[list] = None,
    text_regions_per_frame: Optional[list] = None,
    identity_timeline: Optional[list] = None,
    crop_width_pct: float = 56.25,
) -> dict[str, Any]:
    """Run every applicable parity metric over an AutoFlip-shape
    event list.

    Args:
        events: AutoFlip-shape event list (one per frame).
        face_bboxes_per_frame: Optional per-event face bboxes
            ``[(x, y, w, h), ...]`` in % of source width. ``None``
            means the metric was not measured (older extraction
            cache); the result key is then ``None`` instead of ``0.0``.
        saliency_peaks_per_second: Optional per-second top peak list
            ``[[(x_pct, y_pct, score), ...], ...]``.
        text_regions_per_frame: Optional per-event text bboxes
            (% of source width).
        identity_timeline: Optional per-frame slot-bbox dict
            ``[{"t": float, "slots": {slot_id: (x, y, w, h)}}, ...]``.
        crop_width_pct: Crop width in % of source. Default 56.25 =
            9:16 crop on a 16:9 source. Override for wider crops.

    Returns a dict ready to paste into the markdown rollup. Keys for
    optional metrics are ``None`` when their input was ``None`` —
    this distinguishes "not measured" from "measured zero" so the
    verdict logic doesn't silently grade missing data as a free pass.
    """
    from backend.services.autoflip_parity_metrics import (
        cut_to_hold_ratio,
        face_clipping_rate,
        identity_switch_count,
        max_acceleration,
        max_jerk,
        overlap_count,
        saliency_in_crop_fraction,
        text_region_clipping_rate,
    )

    if not events:
        return {
            "n_segments": 0,
            "note": "empty event list",
            # Even on empty events we surface the keys with None so
            # downstream code doesn't have to KeyError-guard.
            "face_clipping_rate": None,
            "saliency_in_crop_fraction": None,
            "text_region_clipping_rate": None,
            "identity_switch_count": None,
        }

    crop_centers = _derive_crop_centers_pct(events)
    timestamps = [float(e.get("t", 0.0)) for e in events]
    hold = cut_to_hold_ratio(events)

    # overlap_count consumes (start, end) spans; derive from the
    # scene_change flag distribution.
    segment_starts = [float(e["t"]) for e in events if e.get("scene_change")]
    if not segment_starts:
        segment_starts = [float(events[0]["t"])]
    segment_ends = segment_starts[1:] + [float(events[-1]["t"])]
    spans = list(zip(segment_starts, segment_ends))

    # Optional metrics: only compute when the caller actually has data.
    face_clip: Optional[float] = None
    if face_bboxes_per_frame is not None:
        face_clip = face_clipping_rate(
            crop_centers, crop_width_pct, face_bboxes_per_frame,
        )

    sal_in_crop: Optional[float] = None
    if saliency_peaks_per_second is not None:
        sal_in_crop = saliency_in_crop_fraction(
            crop_centers, crop_width_pct, saliency_peaks_per_second,
            timestamps=timestamps,
        )

    text_clip: Optional[float] = None
    if text_regions_per_frame is not None:
        text_clip = text_region_clipping_rate(
            crop_centers, crop_width_pct, text_regions_per_frame,
        )

    id_switches: Optional[int] = None
    if identity_timeline is not None:
        id_switches = identity_switch_count(identity_timeline)

    return {
        "n_segments": hold.get("n_segments", 0),
        "median_hold_sec": hold.get("median_hold_sec"),
        "p25": hold.get("p25"),
        "p75": hold.get("p75"),
        "p95": hold.get("p95"),
        "segments_under_1s_rate": hold.get("segments_under_1s_rate"),
        "segments_over_8s_rate": hold.get("segments_over_8s_rate"),
        "max_acceleration": max_acceleration(crop_centers),
        "max_jerk": max_jerk(crop_centers),
        "overlap_count": overlap_count(spans),
        # New Task 2 metrics. None means "not measured this run."
        "face_clipping_rate": face_clip,
        "saliency_in_crop_fraction": sal_in_crop,
        "text_region_clipping_rate": text_clip,
        "identity_switch_count": id_switches,
    }


def verdict_for(metrics: dict[str, Any], zone: Optional[dict[str, float]]) -> str:
    """Return PASS / MARGINAL / MISS / UNKNOWN for a (clip, tool) pair.

    Task 4 verdict logic:
      - All hold-zone bounds passed AND no Task 2 metric out of zone
        → PASS.
      - Hold zone passed but at least one Task 2 metric out of zone
        → MARGINAL (silently-bad clip; good pacing, wrong subjects).
      - Hold zone failed (median or under_1s out of range) → MISS.
      - No metrics computed (empty events) → UNKNOWN. Empty data is
        not a silent metric.
    """
    if not metrics:
        return "UNKNOWN"
    if metrics.get("n_segments", 0) == 0:
        return "UNKNOWN"
    if zone is None:
        return "UNKNOWN"
    median = metrics.get("median_hold_sec")
    under = metrics.get("segments_under_1s_rate")
    if median is None or under is None:
        return "UNKNOWN"
    in_median = zone["median_hold_min"] <= median <= zone["median_hold_max"]
    under_ok = under <= zone["under_1s_max"]
    hold_zone_pass = in_median and under_ok

    # Task 2 metrics — only enforced when measured (None = not measured).
    extra_failures: list[str] = []
    face_max = zone.get("face_clipping_rate_max")
    sal_min = zone.get("saliency_in_crop_min")
    text_max = zone.get("text_clipping_rate_max")
    id_per_min_max = zone.get("identity_switch_per_min_max")

    fc = metrics.get("face_clipping_rate")
    if face_max is not None and fc is not None and fc > face_max:
        extra_failures.append("face_clipping_rate")
    sal = metrics.get("saliency_in_crop_fraction")
    if sal_min is not None and sal is not None and sal < sal_min:
        extra_failures.append("saliency_in_crop_fraction")
    tc = metrics.get("text_region_clipping_rate")
    if text_max is not None and tc is not None and tc > text_max:
        extra_failures.append("text_region_clipping_rate")
    id_sw = metrics.get("identity_switch_count")
    if id_per_min_max is not None and id_sw is not None:
        # Need clip duration to convert switch count to per-minute rate.
        # Use n_segments × median_hold as a duration proxy when explicit
        # duration isn't surfaced — the bench's events are 1-per-frame
        # so the last - first timestamp would be more accurate, but
        # n_segments × median is good enough for the threshold check.
        n_seg = metrics.get("n_segments") or 0
        med = median or 0.0
        approx_minutes = max((n_seg * med) / 60.0, 1.0 / 60.0)
        per_min = id_sw / approx_minutes
        if per_min > id_per_min_max:
            extra_failures.append("identity_switch_count")

    # Layer 2 (DOVER) quality-delta gate. Fires only when the metrics
    # dict carries the deltas — the bench itself doesn't populate
    # them, but the diagnostics router amends results after the DOVER
    # phase runs. Per-zone overrides win over the module-level default.
    aest_min = zone.get(
        "quality_delta_aesthetic_min", L2_QUALITY_DELTA_AESTHETIC_MIN,
    )
    tech_min = zone.get(
        "quality_delta_technical_min", L2_QUALITY_DELTA_TECHNICAL_MIN,
    )
    aest_delta = metrics.get("quality_delta_aesthetic")
    tech_delta = metrics.get("quality_delta_technical")
    if aest_delta is not None and aest_delta < aest_min:
        extra_failures.append("quality_delta_aesthetic")
    if tech_delta is not None and tech_delta < tech_min:
        extra_failures.append("quality_delta_technical")

    if hold_zone_pass and not extra_failures:
        return "PASS"
    if hold_zone_pass and extra_failures:
        return "MARGINAL"
    if in_median or under_ok:
        return "MARGINAL"
    return "MISS"


# ─────────────────── Pipeline invocation seam ───────────────────


# ─────────────────── Cache / extraction helpers ───────────────────
#
# All of the helpers below do heavy imports lazily inside their own
# bodies so the ``--dry-run`` path of this module stays importable
# in a sandbox without numpy / cv2 / scenedetect / MediaPipe / whisper.


def _synthetic_events_for_clip(clip: dict) -> list[dict]:
    """The legacy ``dry_run`` output: one synthetic event per frame
    at the centered 9:16 crop over the clip's declared duration.

    Kept for backward compatibility with ``--dry-run`` iteration on
    the scoring layer and with the existing harness tests.
    """
    duration = float(clip.get("duration_sec") or 10.0)
    fps = 30.0
    events = []
    n = max(1, int(duration * fps))
    for fi in range(n):
        events.append({
            "frame": fi,
            "t": fi / fps,
            "crop_cx": 0.5,
            "crop_cy": 0.5,
            "crop_w": 0.3164,
            "crop_h": 1.0,
            "scene_change": fi == 0,
        })
    return events


def _default_extraction_cache_dir() -> Path:
    base = os.environ.get(
        "CLIPAI_REAL_CONTENT_CACHE", "/var/cache/clipai/real_content",
    )
    return Path(base) / "extractions"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _repo_root_for_cache() -> Path:
    """Walk up from this file to find the repo root (has ``backend/``)."""
    here = Path(__file__).resolve()
    for p in (here, *here.parents):
        if (p / "backend" / "services").is_dir():
            return p
    return here.parents[2]


def _extractor_module_mtime() -> float:
    """Max mtime across the extractor modules that participate in
    cache invalidation.

    A missing module logs a single WARNING (deduped by path so the
    log doesn't spam) and is skipped from the mtime computation.
    When every module is missing the function returns 0.0 and logs
    ERROR — that situation means the watch list has rotted and the
    operator should investigate, NOT that every cache is forever
    invalid.
    """
    root = _repo_root_for_cache()
    latest = 0.0
    seen_any = False
    for rel in _EXTRACTOR_MODULES_FOR_CACHE:
        p = root / rel
        try:
            mt = p.stat().st_mtime
            seen_any = True
            if mt > latest:
                latest = mt
        except (OSError, FileNotFoundError):
            if rel not in _WARNED_MISSING_MODULES:
                _WARNED_MISSING_MODULES.add(rel)
                logger.warning(
                    "extractor watch list: %s is missing — skipping "
                    "from cache invalidation mtime check. If this "
                    "module was renamed, update _EXTRACTOR_MODULES_FOR_CACHE.",
                    rel,
                )
            continue
    if not seen_any:
        logger.error(
            "extractor watch list: NO modules in _EXTRACTOR_MODULES_FOR_CACHE "
            "were found under %s — cache invalidation is effectively "
            "disabled. The watch list has rotted; investigate before "
            "trusting cached results.",
            root,
        )
        return 0.0
    return latest


def _cache_is_valid(clip_cache: Path) -> bool:
    """Cache is valid iff:
      * the directory exists
      * every required file is present (see _required_cache_files)
      * ``cache_version.txt`` matches the current contract version
      * the cache is at least as new as the extractor modules
    """
    if not clip_cache.is_dir():
        return False
    for name in _required_cache_files():
        if not (clip_cache / name).is_file():
            return False
    try:
        version_raw = (clip_cache / "cache_version.txt").read_text().strip()
        if int(version_raw) != EXTRACTION_CACHE_VERSION:
            return False
    except (OSError, ValueError):
        return False
    try:
        cache_mtime = (clip_cache / "cache_version.txt").stat().st_mtime
    except OSError:
        return False
    if cache_mtime < _extractor_module_mtime():
        return False
    return True


def _read_build_info() -> Optional[str]:
    """Return the container's build timestamp from ``/etc/build_info``.

    The file is written by the final RUN layer in the Dockerfile so
    the diagnostics endpoint can compare cache mtimes against the
    image's age and flag "stale cache, fresh code" mismatches that
    the in-process mtime check might miss (e.g. when a new module
    is added but its path hasn't yet been added to the watch list).

    Returns ``None`` outside of a built container or when the file is
    missing / unreadable.
    """
    try:
        return Path("/etc/build_info").read_text().strip() or None
    except OSError:
        return None


def describe_cache_state(clip_cache: Path) -> dict:
    """Return a JSON-friendly dict describing this clip's cache state.

    Used by ``backend.routers.diagnostics`` to surface a stale-cache
    warning in the SOTA-bench SSE stream and the Settings UI.

    Schema::

        {
          "phase": "cache_check",
          "status": "ok" | "stale_warning" | "miss",
          "cache_path": str,
          "exists": bool,
          "cache_age_seconds": int | None,
          "cache_version": int | None,
          "expected_version": int,
          "container_image_built_at": str | None,
          "warning": str | None,
        }

    ``status`` is:
      - ``"miss"``   when the cache directory does not exist yet.
      - ``"stale_warning"`` when the cache is older than the running
        container image AND older than 24h (operator probably has a
        stale cache from a previous deploy).
      - ``"ok"``     otherwise.
    """
    expected_version = EXTRACTION_CACHE_VERSION
    build_info = _read_build_info()

    if not clip_cache.is_dir():
        return {
            "phase": "cache_check",
            "status": "miss",
            "cache_path": str(clip_cache),
            "exists": False,
            "cache_age_seconds": None,
            "cache_version": None,
            "expected_version": expected_version,
            "container_image_built_at": build_info,
            "warning": None,
        }

    cache_age_seconds: Optional[int] = None
    cache_version: Optional[int] = None
    version_path = clip_cache / "cache_version.txt"
    try:
        if version_path.is_file():
            cache_age_seconds = int(
                max(0.0, time.time() - version_path.stat().st_mtime),
            )
            try:
                cache_version = int(version_path.read_text().strip())
            except (OSError, ValueError):
                cache_version = None
    except OSError:
        pass

    # Compare cache mtime to container build_info. ``build_info`` is
    # an RFC3339 string; we parse it leniently — if it doesn't parse,
    # we fall back to age-only heuristics.
    image_built_epoch: Optional[float] = None
    if build_info:
        try:
            from datetime import datetime, timezone
            image_built_epoch = datetime.fromisoformat(
                build_info.replace("Z", "+00:00"),
            ).replace(tzinfo=timezone.utc).timestamp()
        except (ValueError, TypeError):
            image_built_epoch = None

    is_stale = False
    if cache_age_seconds is not None:
        cache_mtime_epoch = time.time() - cache_age_seconds
        if cache_age_seconds > 86400:
            if image_built_epoch is None:
                # No build_info to compare to: fall back to an age-only
                # heuristic (>24h is suspicious but not necessarily
                # stale; we only warn if version mismatch too).
                if cache_version is not None and cache_version != expected_version:
                    is_stale = True
            elif image_built_epoch > cache_mtime_epoch:
                is_stale = True

    # A version mismatch is unambiguously stale regardless of age.
    if cache_version is not None and cache_version != expected_version:
        is_stale = True

    warning: Optional[str] = None
    if is_stale:
        warning = (
            "Cache predates the running code — re-run with "
            "force-reextract to get fresh numbers."
        )

    return {
        "phase": "cache_check",
        "status": "stale_warning" if is_stale else "ok",
        "cache_path": str(clip_cache),
        "exists": True,
        "cache_age_seconds": cache_age_seconds,
        "cache_version": cache_version,
        "expected_version": expected_version,
        "container_image_built_at": build_info,
        "warning": warning,
    }


def _serialize_shots(shots: list) -> list[dict]:
    return [
        {"index": int(getattr(s, "index", i)),
         "start": float(getattr(s, "start", 0.0)),
         "end": float(getattr(s, "end", 0.0))}
        for i, s in enumerate(shots or [])
    ]


def _serialize_dense_faces(
    dense_faces: list, *, include_embeddings: bool,
) -> list[dict]:
    out: list[dict] = []
    for fr in dense_faces or []:
        row = {
            "timestamp": float(getattr(fr, "timestamp", 0.0)),
            "faces": [],
        }
        for f in getattr(fr, "faces", None) or []:
            face_dict = {
                "nose_x": float(getattr(f, "nose_x", 50.0)),
                "nose_y": float(getattr(f, "nose_y", 50.0)),
                "x": float(getattr(f, "x_center", 50.0)),
                "y": float(getattr(f, "y_center", 50.0)),
                "width": float(getattr(f, "width", 0.0)),
                "height": float(getattr(f, "height", 0.0)),
                "confidence": float(getattr(f, "confidence", 0.0)),
                "lip_aperture": float(getattr(f, "lip_aperture", 0.0)),
                "identity_id": int(getattr(f, "identity_id", -1) or -1),
            }
            if include_embeddings:
                emb = getattr(f, "identity_embedding", None)
                if emb is not None:
                    face_dict["embedding"] = [float(x) for x in emb]
            row["faces"].append(face_dict)
        out.append(row)
    return out


def _serialize_face_registry(face_registry) -> dict:
    if face_registry is None:
        return {"slots": [], "total_frames": 0, "frames_with_faces": 0}
    return {
        "slots": [
            {
                "slot_id": int(getattr(s, "slot_id", i)),
                "nose_x": float(getattr(s, "x_center", 50.0)),
                "width": float(getattr(s, "avg_width", 0.0)),
                "appearances": int(getattr(s, "frame_count", 0)),
            }
            for i, s in enumerate(getattr(face_registry, "slots", []) or [])
        ],
        "total_frames": int(getattr(face_registry, "total_frames", 0)),
        "frames_with_faces": int(
            getattr(face_registry, "frames_with_faces", 0),
        ),
    }


def _serialize_transcript(transcript: list) -> list[dict]:
    out: list[dict] = []
    for seg in transcript or []:
        row = {
            "start": float(getattr(seg, "start", 0.0)),
            "end": float(getattr(seg, "end", 0.0)),
            "text": str(getattr(seg, "text", "") or ""),
            "speaker_id": str(getattr(seg, "speaker", "") or ""),
        }
        words = getattr(seg, "words", None)
        if words:
            row["words"] = [
                {
                    "start": float(getattr(w, "start", 0.0)),
                    "end": float(getattr(w, "end", 0.0)),
                    "word": str(getattr(w, "word", "") or ""),
                }
                for w in words
            ]
        out.append(row)
    return out


def _serialize_speaker_events(events: list) -> list[dict]:
    return [
        {
            "start": float(getattr(e, "start", 0.0)),
            "end": float(getattr(e, "end", 0.0)),
            "slot_id": int(getattr(e, "slot_id", -1) or -1),
            "confidence": float(getattr(e, "confidence", 0.0) or 0.0),
            "on_screen": bool(getattr(e, "on_screen", True)),
        }
        for e in events or []
    ]


def _serialize_content_profile(profile) -> dict:
    if profile is None:
        return {
            "content_type": "unknown",
            "confidence": 0.0,
            "is_multi_speaker_panel": False,
            "is_animated": False,
            "anime_subtype": None,
            "music_subtype": None,
            "gameplay_subtype": None,
            "game_type": "",
        }
    return {
        "content_type": str(
            getattr(profile, "content_type", "unknown") or "unknown",
        ),
        "confidence": float(getattr(profile, "confidence", 0.0) or 0.0),
        "is_multi_speaker_panel": bool(
            getattr(profile, "is_multi_speaker_panel", False),
        ),
        "is_animated": bool(getattr(profile, "is_animated", False)),
        "anime_subtype": getattr(profile, "anime_subtype", None),
        "music_subtype": getattr(profile, "music_subtype", None),
        "gameplay_subtype": getattr(profile, "gameplay_subtype", None),
        "game_type": str(getattr(profile, "game_type", "") or ""),
    }


def _serialize_anime_anchors(anchors: list) -> list[dict]:
    return [
        {
            "timestamp": float(getattr(a, "timestamp", 0.0)),
            "x": float(getattr(a, "x_pct", 50.0)),
            "y": float(getattr(a, "y_pct", 50.0)),
            "score": float(getattr(a, "score", 0.0)),
            "source": str(getattr(a, "source", "fallback")),
        }
        for a in anchors or []
    ]


def _serialize_reframe_segments(segments: list) -> list[dict]:
    """Emit a JSON-friendly list of dicts for ``segments.json``.

    Only the fields the translator + scoring layer care about are
    pinned; the rest are dropped so embeddings / numpy arrays never
    leak into the cache blob.

    ``motion_path`` and ``hard_constraints`` are passed through so the
    diagnostic preview renderer and the events translator can use the
    same per-frame camera path the production export pipeline uses
    (see ``render_plan_keyframes.keyframes_from_cached_render_plan``
    and the smooth interpolation in
    ``export_autoflip_compatible.build_camera_path_keypoints``).
    Each motion_path entry is normalized to a JSON-friendly list of
    ``[t, x]`` (or ``[t, x, y]`` when y is present); ``None`` is
    preserved when the source segment has no path so back-compat with
    callers that test ``"motion_path" in seg`` is maintained.
    """
    out: list[dict] = []
    for s in segments or []:
        raw_path = getattr(s, "motion_path", None)
        motion_path: Optional[list] = None
        if raw_path:
            motion_path = []
            for entry in raw_path:
                # Each entry is (t, x) or (t, x, y); preserve y if present.
                try:
                    items = [float(v) for v in entry]
                except (TypeError, ValueError):
                    continue
                if len(items) >= 2:
                    motion_path.append(items[:3])

        raw_hc = getattr(s, "hard_constraints", None)
        hard_constraints: Optional[list] = None
        if raw_hc:
            hard_constraints = []
            for hc in raw_hc:
                try:
                    items = [float(v) for v in hc]
                except (TypeError, ValueError):
                    continue
                if len(items) >= 4:
                    hard_constraints.append(items[:4])

        out.append({
            "start": float(getattr(s, "start", 0.0)),
            "end": float(getattr(s, "end", 0.0)),
            "subject_x": float(getattr(s, "subject_x", 0.0)),
            "subject_y": float(getattr(s, "subject_y", 0.0)),
            "layout": str(getattr(s, "layout", "single") or "single"),
            "active_slot": getattr(s, "active_slot", None),
            "confidence": float(getattr(s, "confidence", 0.0) or 0.0),
            "reason": str(getattr(s, "reason", "") or ""),
            "ease_in_ms": int(getattr(s, "ease_in_ms", 0) or 0),
            "strategy": str(getattr(s, "strategy", "stationary") or "stationary"),
            "content_type": str(getattr(s, "content_type", "unknown") or "unknown"),
            "motion_path": motion_path,
            "hard_constraints": hard_constraints,
        })
    return out


def _probe_source_metadata(video_path: Path) -> dict:
    """Return ``{width, height, fps, duration}`` via ffprobe. Lazy
    import + subprocess so the module stays sandbox-safe."""
    import subprocess

    cmd = [
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=width,height,r_frame_rate",
        "-show_entries", "format=duration",
        "-of", "json", str(video_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    payload = json.loads(result.stdout or "{}")
    stream = (payload.get("streams") or [{}])[0]
    fmt = payload.get("format") or {}
    width = int(stream.get("width") or 0)
    height = int(stream.get("height") or 0)
    r_frame_rate = stream.get("r_frame_rate") or "30/1"
    if "/" in str(r_frame_rate):
        num, den = str(r_frame_rate).split("/")
        denf = float(den)
        fps = float(num) / denf if denf else float(num)
    else:
        fps = float(r_frame_rate)
    duration = float(fmt.get("duration") or 0.0)
    return {
        "width": width, "height": height, "fps": fps, "duration": duration,
    }


def _compute_saliency_peaks_per_second(
    video_path: Path,
    audio_path: Optional[Path],
    duration: float,
    *,
    slug: str,
) -> list:
    """Layer 1: produce per-second saliency peaks for ``video_path``.

    Sampling: one frame per second via ffmpeg, fed into
    :class:`AvSaliency`. Audio energy at 1 Hz comes from
    :func:`av_saliency.audio_energy_per_second`.

    Returns ``[]`` on any failure path — missing ffmpeg, ImportError on
    ``tasednet``, no GPU, OOM. The bench's saliency-in-crop metric and
    the Layer 1 critic both treat an empty list as "not measured" and
    silently skip the check, so a homelab without TASED-Net installed
    still produces a fully-valid v6 cache.

    Output schema matches ``saliency_in_crop_fraction``:
    ``[[ (x_pct, y_pct, score), ... ]_for_second_0, ...]``.
    """
    if not _saliency_layer_enabled():
        return []
    try:
        from backend.services.av_saliency import (
            AvSaliency, audio_energy_per_second,
        )
    except Exception as exc:
        logger.warning(
            "[%s] saliency layer: import failed (%s) — empty peaks",
            slug, exc,
        )
        return []

    n_seconds = max(1, int(round(duration)))

    # Audio energy (1 Hz). Tolerates missing wav by passing zeros.
    audio_energy_1hz: Any = None
    try:
        import numpy as _np  # noqa: F401  — used inside the try
        if audio_path and Path(audio_path).is_file():
            try:
                import wave
                with wave.open(str(audio_path), "rb") as wf:
                    sr = wf.getframerate()
                    nchan = wf.getnchannels()
                    nframes = wf.getnframes()
                    raw = wf.readframes(nframes)
                import numpy as np
                samples = np.frombuffer(raw, dtype=np.int16)
                if nchan > 1:
                    samples = samples.reshape(-1, nchan).mean(axis=1)
                samples = samples.astype(np.float32) / 32768.0
                audio_energy_1hz = audio_energy_per_second(samples, sr)
            except Exception as exc:
                logger.info(
                    "[%s] saliency layer: audio energy failed (%s) — using zeros",
                    slug, exc,
                )
        if audio_energy_1hz is None:
            import numpy as np
            audio_energy_1hz = np.zeros(n_seconds, dtype=np.float32)
    except Exception as exc:
        logger.info(
            "[%s] saliency layer: numpy unavailable (%s) — empty peaks",
            slug, exc,
        )
        return []

    # Frame sampling at 1 fps via ffmpeg. Output goes to a temp dir so
    # we don't pollute the cache.
    import shutil as _shutil
    import subprocess
    import tempfile
    if not _shutil.which("ffmpeg"):
        logger.info(
            "[%s] saliency layer: ffmpeg not available — empty peaks", slug,
        )
        return []
    tmp = Path(tempfile.mkdtemp(prefix="clipai_saliency_frames_"))
    try:
        cmd = [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(video_path),
            "-vf", "fps=1,scale=256:144",
            str(tmp / "f%04d.png"),
        ]
        try:
            subprocess.run(cmd, check=True, timeout=300, capture_output=True)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            logger.info(
                "[%s] saliency layer: ffmpeg sampling failed (%s) — empty peaks",
                slug, exc,
            )
            return []

        png_paths = sorted(tmp.glob("f*.png"))
        if not png_paths:
            return []
        try:
            import numpy as np
            try:
                import cv2  # type: ignore
            except Exception as exc:
                logger.info(
                    "[%s] saliency layer: cv2 unavailable (%s) — empty peaks",
                    slug, exc,
                )
                return []
            frames = np.stack([
                cv2.cvtColor(cv2.imread(str(p)), cv2.COLOR_BGR2RGB)
                for p in png_paths
            ]).astype(np.uint8)
        except Exception as exc:
            logger.info(
                "[%s] saliency layer: frame load failed (%s) — empty peaks",
                slug, exc,
            )
            return []

        # Determine device — fall back to CPU when GPU not visible.
        from backend.services.av_saliency import _is_gpu_visible
        device = "cuda" if _is_gpu_visible() else "cpu"
        backend_name = "unknown"
        try:
            avs = AvSaliency(device=device)
            backend_name = avs.backend_name
            result = avs.predict(frames, audio_energy_1hz)
        except Exception as exc:
            logger.warning(
                "[%s] saliency layer: AvSaliency.predict failed (%s) — empty peaks",
                slug, exc,
            )
            return []

        # Free the model + GPU memory before the LP solver runs.
        try:
            del avs
            if device == "cuda":
                import torch  # type: ignore
                torch.cuda.empty_cache()
        except Exception:
            pass

        # Stash the chosen backend on the function so the caller can
        # surface it in result.critic.saliency.backend without
        # threading another return value through every call site.
        _compute_saliency_peaks_per_second.last_backend = backend_name  # type: ignore[attr-defined]

        # Serialize peaks: each second is a list of [x_pct, y_pct, score].
        out: list = []
        for sec_peaks in result.peaks:
            out.append([
                [float(x), float(y), float(s)] for (x, y, s) in sec_peaks
            ])
        return out
    finally:
        try:
            _shutil.rmtree(tmp, ignore_errors=True)
        except Exception:
            pass


def _extract_audio_wav(video_path: Path, cache_dir: Path) -> Path:
    """Extract mono 16kHz WAV to ``cache_dir/audio.wav`` via ffmpeg.
    Returns the output path. Lazy subprocess so sandbox-safe.
    """
    import subprocess

    out = cache_dir / "audio.wav"
    cmd = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-i", str(video_path),
        "-ac", "1", "-ar", "16000",
        str(out),
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out


def _transcribe_sync(audio_path: Path) -> list:
    """Synchronous wrapper around ``transcribe_audio``. Lazy import so
    the module stays sandbox-safe; monkeypatched in unit tests so
    whisper doesn't fire."""
    import asyncio
    from backend.services.transcription import transcribe_audio
    return asyncio.run(transcribe_audio(str(audio_path)))


def _classifier_metadata_from_clip(clip: dict) -> dict:
    """Build the ``classify_content`` metadata dict from a manifest
    clip entry, mirroring the mapping ``_run_segmenter`` in
    ``measure_autoflip_parity.py`` uses."""
    metadata: dict = {}
    ct = clip.get("content_type") or ""
    if ct:
        metadata["content_type_override"] = ct
    sub = clip.get("subtype")
    if sub:
        if ct == "anime":
            metadata["anime_subtype"] = sub
        elif ct == "music_video":
            metadata["music_subtype"] = sub
        elif ct in ("gameplay", "stream"):
            metadata["game_type"] = sub
        elif ct == "sports":
            metadata["sports_subtype"] = sub
    return metadata


def _build_anime_features_seq(dense_faces: list) -> list:
    """Build ``AnimeFrameFeatures`` stream from dense face results.
    Mirrors the pipeline's v4 path (face pick + frame-to-frame
    motion delta), minus the OpenCV contrast / saturation cascade.
    """
    from backend.services.anime_anchor import AnimeFrameFeatures

    out: list = []
    prev_x: Optional[float] = None
    prev_y: Optional[float] = None
    for df in dense_faces or []:
        best = None
        best_score = -1.0
        for f in getattr(df, "faces", None) or []:
            conf = float(getattr(f, "confidence", 0.0) or 0.0)
            if conf > best_score:
                best_score = conf
                best = f
        face_x = float(getattr(best, "nose_x", 50.0)) if best else 50.0
        face_y = float(getattr(best, "nose_y", 50.0)) if best else 50.0
        face_score = (
            max(0.0, min(1.0, best_score)) if best is not None else 0.0
        )
        if prev_x is None:
            motion = 0.0
        else:
            motion = min(1.0, (abs(face_x - prev_x) + abs(face_y - prev_y)) / 20.0)
        prev_x, prev_y = face_x, face_y
        out.append(AnimeFrameFeatures(
            timestamp=float(getattr(df, "timestamp", 0.0)),
            face_x_pct=face_x,
            face_y_pct=face_y,
            face_score=face_score,
            motion_energy=motion,
        ))
    return out


def _assert_content_type_routes_to_target(
    clip: dict, content_profile, slug: str,
) -> None:
    """Run ``classify_clip`` and log a warning (not an abort) if the
    classifier's output diverges from the manifest's editorial
    ``target_clipcontenttype``. The divergence itself is a signal
    worth capturing in the harness output."""
    target = str(clip.get("target_clipcontenttype") or "").strip()
    if not target:
        return
    try:
        from backend.services.content_classifier import classify_clip
        got = classify_clip(content_profile=content_profile)
        got_val = getattr(got, "value", str(got))
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning(
            "[%s] classify_clip raised %s — skipping divergence check",
            slug, type(exc).__name__,
        )
        return
    if got_val != target:
        logger.warning(
            "[%s] classify_clip divergence: manifest target=%s "
            "classifier=%s (profile content_type=%s "
            "is_multi_speaker_panel=%s is_animated=%s)",
            slug, target, got_val,
            getattr(content_profile, "content_type", None),
            getattr(content_profile, "is_multi_speaker_panel", None),
            getattr(content_profile, "is_animated", None),
        )


def _extract_and_cache(
    clip: dict,
    video_path: Path,
    clip_cache: Path,
    *,
    cache_embeddings: bool,
) -> dict:
    """Full extraction + segmenter run + cache population.

    Wipes the destination directory before rebuilding so partial
    caches can't leak across runs. Returns the in-memory extraction
    payload so the caller doesn't need a second round trip to disk.
    """
    # Wipe and recreate so partial caches can't leak.
    if clip_cache.exists():
        shutil.rmtree(clip_cache)
    clip_cache.mkdir(parents=True, exist_ok=True)

    slug = str(clip.get("slug") or video_path.stem)
    sha = _sha256_file(video_path)

    # Lazy imports so sandbox stays clean.
    from backend.services.shot_detector import detect_shots
    from backend.services.face_detector import detect_faces_dense
    from backend.services.face_registry import (
        build_face_registry_with_embeddings,
        FaceRegistry,
    )
    from backend.services.content_classifier import classify_content
    from backend.services.active_speaker import (
        build_active_speaker_timeline,
        build_active_speaker_timeline_v2,
    )
    from backend.services.reframe_segmenter import build_reframe_segments
    from backend.services.anime_anchor import (
        USE_ANIME_ANCHOR,
        score_anime_sequence,
    )

    # ── Source metadata via ffprobe ──
    source_meta = _probe_source_metadata(video_path)
    duration = float(source_meta["duration"])
    width = int(source_meta["width"])
    height = int(source_meta["height"])
    fps = float(source_meta["fps"])
    metadata = {
        "slug": slug,
        "sha256": sha,
        "width": width,
        "height": height,
        "fps": fps,
        "duration": duration,
    }
    (clip_cache / "metadata.json").write_text(json.dumps(metadata, indent=2))

    # ── Shots ──
    shots = detect_shots(str(video_path), video_duration=duration) or []
    (clip_cache / "shots.json").write_text(
        json.dumps(_serialize_shots(shots), indent=2),
    )
    shot_cuts = [float(getattr(s, "start", 0.0)) for s in shots]

    # ── Dense faces ──
    dense_faces = detect_faces_dense(
        str(video_path),
        start=0.0,
        end=duration,
        sample_rate=0.5,
        min_confidence=0.4,
        extract_embeddings=True,
    ) or []
    (clip_cache / "dense_faces.json").write_text(
        json.dumps(
            _serialize_dense_faces(
                dense_faces, include_embeddings=cache_embeddings,
            ),
            indent=2,
        ),
    )

    # ── Face registry (embedding-based when we have dense data) ──
    # XC.1: burn-in filter so B-roll / title-card frames don't
    # influence slot discovery. The full ``dense_faces`` list still
    # flows downstream — only registry-input is filtered.
    if dense_faces:
        from backend.services.face_registry import (
            apply_face_registry_burn_in,
        )
        registry_input = apply_face_registry_burn_in(dense_faces)
        face_registry = build_face_registry_with_embeddings(
            registry_input, min_appearances=3, cosine_threshold=0.25,
        )
    else:
        face_registry = FaceRegistry()
    (clip_cache / "face_registry.json").write_text(
        json.dumps(_serialize_face_registry(face_registry), indent=2),
    )

    # ── Audio + transcript ──
    # The audio WAV lives alongside the extraction artifacts so the
    # v2 active-speaker path can reuse it without re-extracting.
    transcript: list = []
    audio_path: Optional[Path] = None
    try:
        audio_path = _extract_audio_wav(video_path, clip_cache)
        transcript = _transcribe_sync(audio_path) or []
    except Exception as exc:
        logger.warning(
            "[%s] audio extraction / transcription failed (non-fatal): %s",
            slug, exc,
        )
        transcript = []
    (clip_cache / "transcript.json").write_text(
        json.dumps(_serialize_transcript(transcript), indent=2),
    )

    # ── Active speaker events ──
    # Task C: mirror the production pipeline's v3 → v2 → v1 fallback
    # chain (pipeline.py around line 4015) so the bench's extracted
    # cache holds the same timeline shape production produces. Without
    # this, the Settings → Validate Test panel showed v2 numbers while
    # production was running v3, and the operator couldn't reason
    # about regressions in either direction.
    speaker_events: list = []
    asd_scores_for_cache: list = []
    asd_backend = _active_asd_backend()
    has_face_data = bool(
        face_registry
        and getattr(face_registry, "multi_speaker", False)
        and transcript
        and dense_faces
    )
    try:
        if asd_backend == "light_asd" and has_face_data:
            try:
                from backend.services.light_asd import score_faces_for_clip
                from backend.services.active_speaker import (
                    build_active_speaker_timeline_v3,
                )
                asd_scores_for_cache = score_faces_for_clip(
                    video_path=str(video_path),
                    face_results=dense_faces,
                    audio_wav_path=str(audio_path) if audio_path else None,
                ) or []
                if asd_scores_for_cache:
                    speaker_events = build_active_speaker_timeline_v3(
                        dense_faces, transcript,
                        asd_scores=asd_scores_for_cache,
                        face_registry=face_registry,
                        window_seconds=0.5,
                        shot_cuts=shot_cuts,
                        audio_path=str(audio_path) if audio_path else None,
                    ) or []
            except Exception as exc:
                logger.warning(
                    "[%s] Light-ASD path failed in bench (non-fatal): %s; "
                    "falling back to v2 heuristic", slug, exc,
                )

        # v2 fallback when v3 is off, the model failed, or scores
        # were empty.
        if not speaker_events and has_face_data:
            speaker_events = build_active_speaker_timeline_v2(
                dense_faces, transcript, face_registry,
                window_seconds=0.5,
                shot_cuts=shot_cuts,
                audio_path=str(audio_path) if audio_path else None,
            ) or []
        # v1 fallback when dense face data isn't available.
        elif (
            not speaker_events
            and face_registry
            and getattr(face_registry, "multi_speaker", False)
            and transcript
        ):
            speaker_events = build_active_speaker_timeline(
                dense_faces, transcript, face_registry,
                window_seconds=2.0,
                shot_cuts=shot_cuts,
                audio_path=str(audio_path) if audio_path else None,
            ) or []
    except Exception as exc:
        logger.warning(
            "[%s] active speaker timeline failed (non-fatal): %s",
            slug, exc,
        )
        speaker_events = []
    (clip_cache / "speaker_events.json").write_text(
        json.dumps(_serialize_speaker_events(speaker_events), indent=2),
    )

    # Task C: persist the per-frame ASD scores so re-runs can reuse
    # them without paying the inference cost twice. Only written when
    # the Light-ASD backend produced scores; the cache validity check
    # only requires this file when CLIPAI_ASD_BACKEND=light_asd, so
    # heuristic-mode caches don't need the file at all.
    if asd_backend == "light_asd":
        (clip_cache / "asd_scores.json").write_text(
            json.dumps([
                {
                    "timestamp": float(getattr(s, "timestamp", 0.0)),
                    "face_idx": int(getattr(s, "face_idx", -1) or -1),
                    "p_speaking": float(getattr(s, "p_speaking", 0.0)),
                }
                for s in asd_scores_for_cache
            ], indent=2),
        )

    # ── Layer 1: per-second saliency peaks (TASED-Net) ──
    # Runs AFTER Whisper / Light-ASD have unloaded so the 4 GB
    # GTX 1650 isn't holding three models at once. Always-write
    # behavior — failure paths produce an empty list rather than
    # crashing the cache. ``CLIPAI_SALIENCY_LAYER=0`` skips the run
    # entirely and writes ``[]`` (also the v6-required schema).
    saliency_peaks: list = []
    saliency_backend: str = "disabled"
    if _saliency_layer_enabled():
        try:
            saliency_peaks = _compute_saliency_peaks_per_second(
                video_path, audio_path, duration, slug=slug,
            )
            saliency_backend = getattr(
                _compute_saliency_peaks_per_second, "last_backend", "unknown",
            ) if saliency_peaks else "failed"
        except Exception as exc:
            logger.warning(
                "[%s] saliency layer raised unexpectedly (%s) — empty peaks",
                slug, exc,
            )
            saliency_peaks = []
            saliency_backend = "failed"
    (clip_cache / "saliency_peaks_per_second.json").write_text(
        json.dumps(saliency_peaks),
    )
    (clip_cache / "saliency_meta.json").write_text(
        json.dumps({"backend": saliency_backend}),
    )

    # ── Content profile ──
    classifier_meta = _classifier_metadata_from_clip(clip)
    content_profile = None
    try:
        content_profile = classify_content(
            shot_cuts=shot_cuts,
            face_registry=face_registry,
            dense_faces=dense_faces,
            scenes=[],
            video_duration=duration,
            metadata=classifier_meta,
            transcript_segments=transcript,
        )
    except Exception as exc:
        logger.warning(
            "[%s] classify_content failed (non-fatal): %s", slug, exc,
        )
    (clip_cache / "content_profile.json").write_text(
        json.dumps(_serialize_content_profile(content_profile), indent=2),
    )

    _assert_content_type_routes_to_target(clip, content_profile, slug)

    # ── Anime anchors (gated) ──
    anime_anchors: list = []
    if (
        content_profile is not None
        and getattr(content_profile, "is_animated", False)
        and USE_ANIME_ANCHOR
    ):
        try:
            features_seq = _build_anime_features_seq(dense_faces)
            anime_anchors = list(score_anime_sequence(
                features_seq,
                anime_subtype=getattr(content_profile, "anime_subtype", None),
            ))
        except Exception as exc:
            logger.warning(
                "[%s] anime anchor extraction failed (non-fatal): %s",
                slug, exc,
            )
            anime_anchors = []
    (clip_cache / "anime_anchors.json").write_text(
        json.dumps(_serialize_anime_anchors(anime_anchors), indent=2),
    )

    # ── Reframe segments ──
    segments = build_reframe_segments(
        shot_cuts=shot_cuts,
        face_registry=face_registry,
        active_speaker_events=speaker_events,
        dense_faces=dense_faces,
        transcript_segments=transcript,
        speaker_to_slot={},
        video_duration=duration,
        source_width=width or 1920,
        source_height=height or 1080,
        job_id=slug,
        content_profile=content_profile,
        persistent_regions=None,
        pacing_estimator=None,
        interpolated_timeline=None,
        frame_saliency=None,
        music_beat_grid=None,
        anime_anchors=anime_anchors or None,
        debug_out={},
    ) or []
    segments_serialized = _serialize_reframe_segments(segments)
    (clip_cache / "segments.json").write_text(
        json.dumps(segments_serialized, indent=2),
    )

    # Stamp the cache version LAST so a crash partway through leaves
    # the directory invalid (required-file check fails).
    (clip_cache / "cache_version.txt").write_text(
        str(EXTRACTION_CACHE_VERSION),
    )

    return {
        "metadata": metadata,
        "segments": segments_serialized,
        "saliency_peaks_per_second": saliency_peaks,
        "saliency_backend": saliency_backend,
    }


def _load_cached_extraction(clip_cache: Path) -> dict:
    metadata = json.loads((clip_cache / "metadata.json").read_text())
    segments = json.loads((clip_cache / "segments.json").read_text())
    payload: dict[str, Any] = {"metadata": metadata, "segments": segments}
    # Task 2 per-frame data — optional. When the cache predates these
    # fields the keys stay missing; ``extract_per_frame_data_from_payload``
    # returns None for each so the metrics report "not measured" instead
    # of "perfect."
    for fname, key in (
        ("face_bboxes_per_frame.json", "face_bboxes_per_frame"),
        ("saliency_peaks_per_second.json", "saliency_peaks_per_second"),
        ("text_regions_per_frame.json", "text_regions_per_frame"),
        ("identity_timeline.json", "identity_timeline"),
    ):
        path = clip_cache / fname
        if path.is_file():
            try:
                payload[key] = json.loads(path.read_text())
            except (OSError, json.JSONDecodeError) as exc:
                logger.warning(
                    "extraction cache: failed to load %s: %s", fname, exc,
                )
    # Layer 1 backend metadata (which adapter actually ran). Optional —
    # caches written before saliency_meta.json existed return None.
    meta_path = clip_cache / "saliency_meta.json"
    if meta_path.is_file():
        try:
            payload["saliency_backend"] = json.loads(
                meta_path.read_text()
            ).get("backend")
        except (OSError, json.JSONDecodeError):
            pass
    return payload


def _count_saliency_flagged_windows(
    events: list, saliency_peaks_per_second: Optional[list],
    *, crop_width_pct: float = 56.25,
) -> int:
    """Count seconds where every top-K saliency peak lies outside the
    crop, mirroring the ``saliency_excluded`` flag in
    ``reframe_critic._saliency_in_crop_at`` (Layer 1).

    Returns 0 when no peaks data is available — "not measured" rather
    than "everything is fine."
    """
    if not events or not saliency_peaks_per_second:
        return 0
    half = crop_width_pct / 2.0
    # Bucket events by integer second; use the median crop center
    # within each second to avoid sub-second jitter.
    seconds: dict[int, list[float]] = {}
    for e in events:
        try:
            t = float(e.get("t", 0.0))
            cx = float(e.get("crop_cx", 0.5)) * 100.0
        except (TypeError, ValueError):
            continue
        seconds.setdefault(int(t), []).append(cx)
    flagged = 0
    for sec_idx, peaks in enumerate(saliency_peaks_per_second):
        if not peaks:
            continue
        cxs = seconds.get(sec_idx)
        if not cxs:
            continue
        cxs_sorted = sorted(cxs)
        cx = cxs_sorted[len(cxs_sorted) // 2]  # median
        any_in = False
        for peak in peaks:
            try:
                px = float(peak[0])
            except (TypeError, ValueError, IndexError):
                continue
            if cx - half <= px <= cx + half:
                any_in = True
                break
        if not any_in:
            flagged += 1
    return flagged


def extract_per_frame_data_from_payload(payload: dict) -> dict[str, Optional[list]]:
    """Return the four optional per-frame structures Task 2 metrics need.

    Older extraction caches don't have these — for those, every value
    is ``None``. The bench treats ``None`` as "not measured" which keeps
    missing data from being silently scored as a perfect zero.
    """
    return {
        "face_bboxes_per_frame": payload.get("face_bboxes_per_frame"),
        "saliency_peaks_per_second": payload.get("saliency_peaks_per_second"),
        "text_regions_per_frame": payload.get("text_regions_per_frame"),
        "identity_timeline": payload.get("identity_timeline"),
    }


def run_clipai_on_clip(
    clip: dict,
    video_path: Optional[Path],
    *,
    dry_run: bool = False,
    cache_dir: Optional[Path] = None,
    cache_embeddings: bool = False,
    force_reextract: bool = False,
    extras_out: Optional[dict] = None,
) -> Optional[list[dict]]:
    """Produce a ClipAI timeline event list for a clip.

    Two operating modes:

    1. ``dry_run=True`` or ``video_path is None`` — returns the
       legacy synthetic one-frame-per-frame timeline so the
       ``--dry-run`` iteration path (scoring-layer-only work)
       stays fast and sandbox-safe. This is the same shape the
       existing harness tests pin.

    2. Real invocation — resolves the extraction cache under
       ``cache_dir`` (or ``$CLIPAI_REAL_CONTENT_CACHE/extractions``),
       runs the full extraction stack (shots → dense faces →
       registry → transcript → active speaker → content profile →
       anime anchors → reframe segments) when the cache is cold,
       and translates the segment list via
       ``export_autoflip_compatible.reframe_segments_to_events``.

    Returns ``None`` when the video path is supplied but does not
    exist on disk — the harness reports that row as
    ``clipai_skipped``.
    """
    # ── Synthetic / dry-run path ──
    if dry_run or video_path is None:
        return _synthetic_events_for_clip(clip)

    slug = str(clip.get("slug") or "")

    # ── Missing file → skipped row ──
    video_path = Path(video_path)
    if not video_path.is_file():
        logger.warning(
            "[%s] run_clipai_on_clip: video not found at %s — returning None",
            slug, video_path,
        )
        return None

    # ── Resolve cache dir ──
    resolved_cache_dir = (
        Path(cache_dir) if cache_dir is not None
        else _default_extraction_cache_dir()
    )

    try:
        sha = _sha256_file(video_path)
    except OSError as exc:
        logger.warning(
            "[%s] failed to hash %s: %s — returning None",
            slug, video_path, exc,
        )
        return None

    clip_cache = resolved_cache_dir / sha

    if not force_reextract and _cache_is_valid(clip_cache):
        logger.info(
            "[%s] extraction cache HIT at %s", slug, clip_cache,
        )
        payload = _load_cached_extraction(clip_cache)
    else:
        logger.info(
            "[%s] extraction cache MISS at %s — running full extraction",
            slug, clip_cache,
        )
        try:
            payload = _extract_and_cache(
                clip, video_path, clip_cache,
                cache_embeddings=cache_embeddings,
            )
        except Exception as exc:
            logger.warning(
                "[%s] extraction failed: %s — returning None",
                slug, exc,
            )
            return None

    metadata = payload.get("metadata") or {}
    segments = payload.get("segments") or []
    src_w = int(metadata.get("width") or 1920)
    src_h = int(metadata.get("height") or 1080)
    fps = float(metadata.get("fps") or 30.0)

    # Lazy import of the translator so the dry-run path stays
    # sandbox-safe (the translator itself is pure, but the import
    # sits next to the ffprobe helper we DON'T want to drag along).
    from backend.scripts.export_autoflip_compatible import (
        reframe_segments_to_events,
    )
    events = reframe_segments_to_events(
        segments, src_w, src_h, fps, aspect_ratio="9:16",
    )
    if extras_out is not None:
        extras_out.update(extract_per_frame_data_from_payload(payload))
        # ``saliency_backend`` is consumed by the result.critic block
        # in main(), not by ``score_timeline`` (which would reject the
        # unknown kwarg). Stash it under a leading-underscore key the
        # caller pops before splatting extras into score_timeline.
        backend = payload.get("saliency_backend")
        if backend is not None:
            extras_out["_saliency_backend"] = backend
    return events


def load_autoflip_timeline(
    clip: dict, autoflip_dir: Path,
    *,
    return_tool: bool = False,
) -> Optional[list[dict]] | tuple[Optional[list[dict]], Optional[str]]:
    """Load the AutoFlip-shape event list for one clip.

    When ``return_tool`` is True, returns ``(events, tool_label)``
    where ``tool_label`` is the JSON's ``tool`` field — typically
    one of ``autoflip_real``, ``autoflip_prebuilt``, or
    ``naive_baseline``. The legacy single-return shape is preserved
    (``return_tool`` defaults to False) so older callers keep working.
    """
    slug = clip["slug"]
    path = autoflip_dir / f"{slug}.json"
    if not path.is_file():
        if return_tool:
            return None, None
        return None
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("[%s] AutoFlip JSON load failed: %s", slug, e)
        if return_tool:
            return None, None
        return None
    events = payload.get("events") or []
    tool = payload.get("tool")
    if not events:
        if return_tool:
            return None, tool
        return None
    if return_tool:
        return events, tool
    return events


def load_ground_truth_timeline(
    clip: dict, ground_truth_dir: Path,
) -> Optional[list[dict]]:
    slug = clip["slug"]
    path = ground_truth_dir / f"{slug}.json"
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    return payload.get("events") or None


# ─────────────────── Rollup rendering ───────────────────


_GROUP_ORDER = [
    ("panels", {"multi_speaker_panel"}),
    ("anime", {"animation", "animation_dialogue"}),
    ("sports", {"sports", "sports_basketball", "sports_racing"}),
    ("music", {"music_video"}),
]


def _group_for(clip: dict) -> str:
    ct = clip.get("target_clipcontenttype") or ""
    for group_name, cts in _GROUP_ORDER:
        if ct in cts:
            return group_name
    return "other"


def _fmt(v: Any, digits: int = 2, missing: str = "—") -> str:
    if v is None:
        return missing
    if isinstance(v, (int, float)):
        return f"{v:.{digits}f}"
    return str(v)


def render_markdown(
    results: list[ClipResult],
    *,
    autoflip_outputs_dir: Path,
    clipai_invocation: str,
) -> str:
    """Emit the per-group markdown rollup."""
    by_group: dict[str, list[ClipResult]] = {}
    for r in results:
        by_group.setdefault(
            _group_for({
                "target_clipcontenttype": r.target_clipcontenttype,
                "subtype": r.subtype,
            }),
            [],
        ).append(r)

    out: list[str] = []
    out.append("# Week 3 — Real-content comparison results\n")
    out.append(
        "Generated by "
        "`backend/scripts/compare_autoflip_vs_clipai.py`. Each row is "
        "one (clip, tool) pair. Verdict uses the per-content-type "
        "target zone from `TARGET_ZONES` when no human ground-truth "
        "sidecar is available.\n"
    )
    # Task 5A — surface which tool produced each AutoFlip cell so a
    # SOTA claim isn't accidentally made against the naive strawman.
    af_tools = [r.autoflip_tool for r in results if r.autoflip_tool]
    real_count = sum(1 for t in af_tools if t in ("autoflip_real", "autoflip_prebuilt"))
    naive_count = sum(1 for t in af_tools if t == "naive_baseline")
    out.append(
        f"- Clips scored: **{len(results)}**\n"
        f"- AutoFlip outputs dir: `{autoflip_outputs_dir}`\n"
        f"- AutoFlip references: {real_count} real, {naive_count} naive_baseline\n"
        f"- ClipAI invocation mode: `{clipai_invocation}`\n"
    )
    if naive_count > 0 and real_count == 0:
        out.append(
            "\n> **Warning** — every AutoFlip column on this run was "
            "produced by the naive center-crop baseline, not real "
            "MediaPipe AutoFlip. Run `make autoflip-references` to "
            "regenerate against the real comparator before making any "
            "SOTA claims.\n"
        )

    for group, cts in _GROUP_ORDER:
        group_results = by_group.get(group) or []
        if not group_results:
            continue
        out.append(f"\n## {group.title()}\n")
        out.append(
            "| Clip | Tool | median | p25 | p75 | under_1s | over_8s | "
            "max_accel | max_jerk | verdict |\n"
        )
        out.append(
            "|---|---|---|---|---|---|---|---|---|---|\n"
        )
        # Per-row autoflip label depends on the source JSON's tool
        # field so the markdown column reads "autoflip (real)" vs
        # "autoflip (naive)" distinctly.
        _AUTOFLIP_LABEL_MAP = {
            "autoflip_real": "autoflip (real)",
            "autoflip_prebuilt": "autoflip (prebuilt)",
            "naive_baseline": "autoflip (naive)",
        }
        for r in group_results:
            af_label = _AUTOFLIP_LABEL_MAP.get(
                r.autoflip_tool or "", "autoflip",
            )
            for tool, label in (
                ("autoflip", af_label),
                ("clipai", "**clipai**"),
                ("ground_truth", "ground_truth"),
            ):
                m = getattr(r, tool)
                if m is None:
                    out.append(
                        f"| `{r.slug}` | {label} | "
                        f"— | — | — | — | — | — | — | SKIPPED |\n"
                    )
                    continue
                out.append(
                    f"| `{r.slug}` | {label} | "
                    f"{_fmt(m.get('median_hold_sec'))} | "
                    f"{_fmt(m.get('p25'))} | "
                    f"{_fmt(m.get('p75'))} | "
                    f"{_fmt(m.get('segments_under_1s_rate'), 2)} | "
                    f"{_fmt(m.get('segments_over_8s_rate'), 2)} | "
                    f"{_fmt(m.get('max_acceleration'))} | "
                    f"{_fmt(m.get('max_jerk'))} | "
                    f"{r.verdicts.get(tool, 'UNKNOWN')} |\n"
                )
            if r.notes:
                out.append(
                    f"| | _{' · '.join(r.notes)}_ | | | | | | | | |\n"
                )
    return "".join(out)


# ─────────────────── Main loop ───────────────────


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", default="tests/real_content/manifest.json",
    )
    parser.add_argument(
        "--autoflip-outputs",
        default="tests/autoflip_reference_outputs",
    )
    parser.add_argument(
        "--ground-truth-dir",
        default="tests/real_content/ground_truth",
    )
    parser.add_argument(
        "--output",
        default="docs/week3_real_content_results.md",
    )
    parser.add_argument(
        "--json-out",
        default="/tmp/week3_results.json",
    )
    parser.add_argument(
        "--filter", default="*",
        help="Only score clips whose slug matches the glob",
    )
    parser.add_argument(
        "--filter-slugs", default=None,
        help=(
            "Comma-separated list of exact slugs to score. Applied "
            "after --filter. When unset (default) every clip that "
            "matches --filter runs."
        ),
    )
    parser.add_argument(
        "--clipai-only", action="store_true",
        help="Skip AutoFlip load (mark every clip's autoflip as SKIPPED)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Emit stubbed ClipAI timelines without invoking the pipeline",
    )
    parser.add_argument(
        "--real-content-dir", default=None,
        help=(
            "Directory containing the resolved clip videos. Defaults "
            "to $CLIPAI_REAL_CONTENT_CACHE (/var/cache/clipai/real_content "
            "if unset). Each clip is looked up as <dir>/<slug>.<ext>."
        ),
    )
    parser.add_argument(
        "--extraction-cache-dir", default=None,
        help=(
            "Directory for the per-clip extraction cache "
            "($CLIPAI_REAL_CONTENT_CACHE/extractions by default)."
        ),
    )
    parser.add_argument(
        "--cache-embeddings", action="store_true",
        help="Persist identity embeddings in dense_faces.json (large).",
    )
    parser.add_argument(
        "--force-reextract", action="store_true",
        help="Ignore the extraction cache and rebuild every clip.",
    )
    parser.add_argument(
        "--quiet", action="store_true",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    manifest_path = Path(args.manifest)
    if not manifest_path.is_file():
        logger.error("manifest not found at %s", manifest_path)
        return 2
    manifest = json.loads(manifest_path.read_text())

    autoflip_dir = Path(args.autoflip_outputs)
    gt_dir = Path(args.ground_truth_dir)

    # ── Resolve real-content + extraction cache roots ──
    real_content_dir = (
        Path(args.real_content_dir) if args.real_content_dir
        else Path(os.environ.get(
            "CLIPAI_REAL_CONTENT_CACHE", "/var/cache/clipai/real_content",
        ))
    )
    extraction_cache_dir = (
        Path(args.extraction_cache_dir) if args.extraction_cache_dir
        else _default_extraction_cache_dir()
    )

    results: list[ClipResult] = []
    filter_glob = args.filter
    slug_whitelist: Optional[set[str]] = None
    if args.filter_slugs:
        slug_whitelist = {
            s.strip() for s in args.filter_slugs.split(",") if s.strip()
        }

    for clip in manifest.get("clips", []):
        slug = clip.get("slug") or ""
        if not fnmatch.fnmatch(slug, filter_glob):
            continue
        if slug_whitelist is not None and slug not in slug_whitelist:
            continue

        result = ClipResult(
            slug=slug,
            content_type=clip.get("content_type") or "",
            target_clipcontenttype=clip.get("target_clipcontenttype") or "",
            subtype=clip.get("subtype"),
        )

        # AutoFlip timeline
        if args.clipai_only:
            result.notes.append("autoflip skipped (--clipai-only)")
        else:
            af_events, af_tool = load_autoflip_timeline(
                clip, autoflip_dir, return_tool=True,
            )
            result.autoflip_tool = af_tool
            if af_events is None:
                result.notes.append(
                    f"no AutoFlip cache at {autoflip_dir}/{slug}.json"
                )
            else:
                result.autoflip = score_timeline(af_events)
                if af_tool == "naive_baseline":
                    result.notes.append(
                        "autoflip column is naive_baseline (Path B "
                        "fallback) — re-run 'make autoflip-references' "
                        "for real comparison"
                    )

        # ClipAI timeline
        # Resolve the on-disk video path from the real-content dir,
        # using the manifest's slug + ext. In dry-run mode we pass
        # None so the synthetic path fires regardless.
        if args.dry_run:
            _video_path = None
        else:
            _ext = str(clip.get("ext") or "mp4")
            _candidate = real_content_dir / f"{slug}.{_ext}"
            _video_path = _candidate if _candidate.is_file() else None
            if _video_path is None:
                result.notes.append(
                    f"no clip at {_candidate}"
                )
        ca_extras: dict = {}
        ca_events = run_clipai_on_clip(
            clip,
            video_path=_video_path,
            dry_run=args.dry_run,
            cache_dir=extraction_cache_dir,
            cache_embeddings=args.cache_embeddings,
            force_reextract=args.force_reextract,
            extras_out=ca_extras,
        )
        if ca_events is None:
            if args.dry_run:
                result.notes.append("clipai pipeline invocation not wired")
            else:
                result.notes.append("clipai_skipped")
        else:
            # Layer 1: pop the out-of-band saliency backend before
            # splatting extras into score_timeline (which only accepts
            # the documented per-frame kwargs).
            sal_backend = ca_extras.pop("_saliency_backend", None)
            result.clipai = score_timeline(ca_events, **ca_extras)
            # Layer 1: surface saliency-in-crop into the critic block
            # so the UI / JSON consumer can render the Critic Engine
            # rows. We compute ``windows_flagged`` here from the same
            # peaks + crop centers the in-crop fraction uses, so the
            # bench reports a real number even though it doesn't run
            # ``auto_repair_plan`` directly. ``windows_fixed`` stays
            # None until the bench drives the bridge end-to-end —
            # production exports already get the fixes via
            # ``human_reframe_bridge.maybe_override_render_plan``.
            sal_peaks = ca_extras.get("saliency_peaks_per_second")
            sal_in_crop = (
                result.clipai.get("saliency_in_crop_fraction")
                if isinstance(result.clipai, dict) else None
            )
            if (
                sal_peaks is not None
                or sal_in_crop is not None
                or sal_backend
            ):
                # Count seconds where every top-K peak fell outside the
                # crop window — these are the "flagged" windows the
                # critic would auto-widen during the production export.
                windows_flagged = _count_saliency_flagged_windows(
                    ca_events, sal_peaks,
                )
                result.critic = {
                    "saliency": {
                        "in_crop_fraction": sal_in_crop,
                        # Alias used by the UI's Critic engine row —
                        # same value, more readable key.
                        "in_crop_mean": sal_in_crop,
                        "n_seconds_with_peaks": (
                            sum(1 for s in (sal_peaks or []) if s)
                        ),
                        "windows_flagged": windows_flagged,
                        "windows_fixed": None,
                        "backend": sal_backend,
                    },
                }

        # Optional human ground truth
        gt_events = load_ground_truth_timeline(clip, gt_dir)
        if gt_events:
            result.ground_truth = score_timeline(gt_events)

        # Verdicts
        zone = target_zone_for(clip)
        for tool in ("autoflip", "clipai", "ground_truth"):
            m = getattr(result, tool)
            if m is None:
                continue
            result.verdicts[tool] = verdict_for(m, zone)

        results.append(result)

    # Emit markdown
    md_body = render_markdown(
        results,
        autoflip_outputs_dir=autoflip_dir,
        clipai_invocation=(
            "stub (dry_run=True)" if args.dry_run
            else f"real (cache={extraction_cache_dir})"
        ),
    )
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(md_body)
    logger.info("wrote markdown rollup to %s", args.output)

    # Emit JSON dump
    payload = {
        "schema": "week3_real_content_results/1",
        "manifest_path": str(manifest_path),
        "autoflip_outputs_dir": str(autoflip_dir),
        "filter": args.filter,
        "filter_slugs": (
            sorted(slug_whitelist) if slug_whitelist is not None else None
        ),
        "results": [
            {
                "slug": r.slug,
                "content_type": r.content_type,
                "target_clipcontenttype": r.target_clipcontenttype,
                "subtype": r.subtype,
                "autoflip": r.autoflip,
                "autoflip_tool": r.autoflip_tool,
                "clipai": r.clipai,
                "ground_truth": r.ground_truth,
                "verdicts": r.verdicts,
                "notes": r.notes,
                "critic": r.critic,
            }
            for r in results
        ],
    }
    Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json_out).write_text(json.dumps(payload, indent=2))
    logger.info("wrote JSON dump to %s", args.json_out)

    return 0


if __name__ == "__main__":
    sys.exit(main())
