"""ffmpeg-required integration smoke tests for the SOTA preview x-expression.

The expression generated by ``sota_render_preview._build_x_expression``
is consumed by ffmpeg's ``crop`` filter. These tests confirm that the
generated expression PARSES under a real ffmpeg (no syntax errors, no
operator-precedence surprises) and produces a correctly-positioned
crop on a synthetic test source for both:

  * a tracking shot with a smooth motion_path pan, and
  * a cached back-compat legacy step (no motion_path).

Both tests are SKIPPED when ffmpeg is not on PATH so the QA sandbox
stays green without a media stack installed.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from backend.scripts.sota_render_preview import _build_x_expression

ffmpeg_bin = shutil.which("ffmpeg")
needs_ffmpeg = pytest.mark.skipif(
    ffmpeg_bin is None,
    reason="ffmpeg not installed on this host",
)


def _build_test_source(out_path: Path, width: int, height: int, dur: float) -> None:
    """Render a deterministic 1920x1080 ``testsrc2`` clip — a built-in
    ffmpeg pattern source. The exact pixels don't matter for the
    parse/render contract; we only need a valid input the crop
    filter can pull frames from.
    """
    cmd = [
        ffmpeg_bin, "-y", "-loglevel", "error",
        "-f", "lavfi",
        "-i", f"testsrc2=s={width}x{height}:d={dur}:r=30",
        "-c:v", "libx264", "-preset", "ultrafast",
        "-pix_fmt", "yuv420p",
        str(out_path),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _crop_with_expression(
    src: Path, dst: Path, x_expr: str, crop_w: int, crop_h: int,
) -> None:
    """Run the same ffmpeg command the production renderer uses."""
    vf = (
        f"crop=w={crop_w}:h={crop_h}:x='{x_expr}':y=0,"
        f"scale=540:960:flags=lanczos,setsar=1"
    )
    cmd = [
        ffmpeg_bin, "-y", "-loglevel", "error",
        "-i", str(src),
        "-vf", vf,
        "-c:v", "libx264", "-preset", "ultrafast",
        str(dst),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _output_is_nonempty(path: Path) -> bool:
    return path.is_file() and path.stat().st_size > 1024


@needs_ffmpeg
def test_tracking_expression_parses_and_renders(tmp_path):
    """The motion_path lerp expression should parse and produce a
    non-empty cropped output under a real ffmpeg."""
    src = tmp_path / "src.mp4"
    dst = tmp_path / "tracked.mp4"
    src_w, src_h, dur = 1920, 1080, 4.0
    _build_test_source(src, src_w, src_h, dur)

    crop_w = int(round(src_h * 9 / 16))  # 608
    segs = [{
        "start": 0.0, "end": dur,
        "subject_x": 225.0,
        "motion_path": [
            (0.0, 225.0),
            (1.0, 600.0),
            (2.0, 975.0),
            (3.0, 1350.0),
            (4.0, 1725.0),
        ],
    }]
    x_expr = _build_x_expression(segs, src_w, crop_w)

    # Should NOT contain the legacy ``between(t,...)`` syntax.
    assert "between(t" not in x_expr
    _crop_with_expression(src, dst, x_expr, crop_w, src_h)
    assert _output_is_nonempty(dst), (
        f"expected non-empty output at {dst}; "
        f"ffmpeg likely rejected the expression"
    )


@needs_ffmpeg
def test_legacy_step_expression_back_compat(tmp_path):
    """A cached segments.json without motion_path should produce a
    held-x step expression that parses and renders under ffmpeg."""
    src = tmp_path / "src.mp4"
    dst = tmp_path / "stepped.mp4"
    src_w, src_h, dur = 1920, 1080, 4.0
    _build_test_source(src, src_w, src_h, dur)

    crop_w = int(round(src_h * 9 / 16))  # 608
    segs = [
        {"start": 0.0, "end": 2.0, "subject_x": 400.0},
        {"start": 2.0, "end": 4.0, "subject_x": 1500.0},
    ]
    x_expr = _build_x_expression(segs, src_w, crop_w)
    _crop_with_expression(src, dst, x_expr, crop_w, src_h)
    assert _output_is_nonempty(dst), (
        f"expected non-empty output at {dst}; "
        f"ffmpeg likely rejected the expression"
    )
